name: FullCloak
version: ${project.version}
main: com.gmail.davideblade99.fullcloak.FullCloak
author: DavideBlade
description: ${project.description}
load: POSTWORLD
website: https://www.spigotmc.org/resources/fullcloak.98851/
database: false
softdepend: [CombatTagPlus]
commands:
  fullcloak:
    usage: /<command> [help|off|disable|enable|cooldown|check|open|effect|hide|reload]
    aliases: fc
    description: Plugin information.

permissions:
  fullcloak.*:
    description: Gives access to all permissions of FullCloak.
    children:
      fullcloak.hide: true
      fullcloak.hide.10: true
      fullcloak.hide.20: true
      fullcloak.hide.30: true
      fullcloak.hide.40: true
      fullcloak.hide.50: true
      fullcloak.hide.60: true
      fullcloak.see: true
      fullcloak.commands.*: true
  fullcloak.commands.*:
    description: Gives access to all commands of FullCloak.
    children:
      fullcloak.command.off: true
      fullcloak.command.cooldown: true
      fullcloak.command.enable: true
      fullcloak.command.disable: true
      fullcloak.command.check: true
      fullcloak.command.open: true
      fullcloak.command.effect: true
      fullcloak.command.hide: true
      fullcloak.command.reload: true
  fullcloak.hide:
    description: Allows becoming invisible while you are crouching.
    default: op
  fullcloak.hide.10:
    description: Allows becoming invisible for 10 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.hide.20:
    description: Allows becoming invisible for 20 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.hide.30:
    description: Allows becoming invisible for 30 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.hide.40:
    description: Allows becoming invisible for 40 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.hide.50:
    description: Allows becoming invisible for 50 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.hide.60:
    description: Allows becoming invisible for 60 seconds.
    default: op
    children:
      fullcloak.hide: true
  fullcloak.see:
    description: Allows to see invisible players.
    default: op
  fullcloak.command.off:
    description: Allows you to use the command /fullcloak off.
    default: op
  fullcloak.command.cooldown:
    description: Allows you to use the command /fullcloak cooldown.
    default: op
  fullcloak.command.enable:
    description: Allows you to use the command /fullcloak enable.
    default: op
  fullcloak.command.disable:
    description: Allows you to use the command /fullcloak disable.
    default: op
  fullcloak.command.check:
    description: Allows you to use the command /fullcloak check.
    default: op
  fullcloak.command.open:
    description: Allows you to use the command /fullcloak open.
    default: op
  fullcloak.command.effect:
    description: Allows you to use the command /fullcloak effect.
    default: op
  fullcloak.command.hide:
    description: Allows you to use the command /fullcloak hide.
    default: op
  fullcloak.command.reload:
    description: Allows you to use the command /fullcloak reload.
    default: op